services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vote_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - '5540:5540'
    restart: unless-stopped

volumes:
  redis-data:
  pgdata:
